<?php 
session_start();
if(isset($_SESSION["MEMBER_ID"]) === true){
	$result = array(
		"MEMBER_ID"=>$_SESSION["MEMBER_ID"], 
		"MEMBER_PSW"=>$_SESSION["MEMBER_PSW"], 
		"MEMBER_NAME"=>$_SESSION["MEMBER_NAME"], 
		"MEMBER_AGE"=>$_SESSION["MEMBER_AGE"], 
		"MEMBER_SEX"=>$_SESSION["MEMBER_SEX"], 
		"MEMBER_EMAIL"=>$_SESSION["MEMBER_EMAIL"], 
		"MEMBER_IMAGE"=>$_SESSION["MEMBER_IMAGE"], 
		"MEMBER_INTRODUCTION"=>$_SESSION["MEMBER_INTRODUCTION"], 
		"GROUP_NO"=>$_SESSION["GROUP_NO"], 
		"GROUP_NAME"=>$_SESSION["GROUP_NAME"], 
		"RES_NAME"=>$_SESSION["RES_NAME"], 
		"STYLE_NAME"=>$_SESSION["STYLE_NAME"], 
		"KIND_NAME"=>$_SESSION["KIND_NAME"], 
		"COMMANDER"=>$_SESSION["COMMANDER"], 
		"JOIN_NUMBER"=>$_SESSION["JOIN_NUMBER"], 
		"MEAL_TIME"=>$_SESSION["MEAL_TIME"], 
		"RES_ADDRESS"=>$_SESSION["RES_ADDRESS"], 
		"RES_TEL"=>$_SESSION["RES_TEL"], 
		"RES_BUS_HOURS"=>$_SESSION["RES_BUS_HOURS"], 
		"MAIN_IMG"=>$_SESSION["RES_IMAGE1"], 
		"RES_IMAGE1"=>$_SESSION["RES_IMAGE1"], 
		"RES_IMAGE2"=>$_SESSION["RES_IMAGE2"], 
		"RES_IMAGE3"=>$_SESSION["RES_IMAGE3"], 
		"RES_IMAGE4"=>$_SESSION["RES_IMAGE4"], 

	);
	$json = json_encode($result);
	echo json_encode($result);
}else{
	echo "{}";
}
?>